name: pyBKB_v3
channels:
  - conda-forge
dependencies:
  - python=3
  - numpy
  - matplotlib
  - cartopy
  - jupyter
  - jupyterlab
  - netcdf4
  - pandas
  - scipy
  - metpy
  - siphon
  - xarray
  - basemap
  - basemap-data-hires
  - dask
  - pyproj
  - h5py
  #- pygrib # Not availalbe on Windows
